name: Show retrigger command
description: Add a section to the workflow’s summary to show a command to retrigger it

inputs:
  workflow-inputs:
    description: JSON object of the inputs passed to the workflow
    required: true

runs:
  using: composite
  steps:
  - name: Show retrigger command
    env:
      ACTION_PATH: ${{ github.action_path }}
      REPO: ${{ github.repository }}
      REF: ${{ github.ref_name }}
      WF_REF: ${{ github.workflow_ref }}
      WF_INPUTS: ${{ inputs.workflow-inputs }}
    run: |-
      "${ACTION_PATH}"/show-retrigger-command.py \
        --repo "${REPO}" \
        --ref "${REF}" \
        --workflow-ref "${WF_REF}" \
        --inputs "${WF_INPUTS}" >> "${GITHUB_STEP_SUMMARY}"
    shell: bash
