name: checking out comparisons with 'none'

on:
  workflow_dispatch:
    inputs:
      zero:
        description: branch-one
        required: true
        type: string
        default: 'main'
      one:
        description: branch-two
        required: false
        type: string
        default: 'main'

jobs:
  COMPARISONS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log inputs
        run: |-
          echo "inputs.zero=${{ inputs.zero }}"
          echo "inputs.one=${{ inputs.one }}"
        shell: bash

      - name: required input
        uses: ./.github/actions/compare
        with:
          branch: ${{ inputs.zero }}

      - name: optional input
        uses: ./.github/actions/compare
        with:
          branch: ${{ inputs.one }}

      - name: required input
        uses: ./.github/actions/compare
        with:
          branch: ${{ inputs.zero || 'default' }}

      - name: optional input
        uses: ./.github/actions/compare
        with:
          branch: ${{ inputs.one || 'default' }}
