name: "on-read-labeled PR action"

on:
  pull_request:
    branches: [main]
    types: [labeled, synchronize]
  push:
    branches: [main]

jobs:
  UV:
    runs-on: ubuntu-latest
    steps:
      - name: Install a semver range of uv
        uses: astral-sh/setup-uv@v6
      - name: Install a semver range of uv
        uses: astral-sh/setup-uv@v6
