name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      blessed: steps.blessed.outputs.BLESSED
      doomed: steps.doomed.outputs.DOOMED

    steps:
      - name: blessed
        id: blessed
        run: echo "BLESSED=1" >> $GITHUB_OUTPUT

      - name: plain
        if: success() || failure() && steps.blessed.outputs.BLESSED == '1'
        run: echo "hi"
      - name: plain logic-nested
        if: (success() || failure()) && steps.blessed.outputs.BLESSED == '1'
        run: echo "hi"

      - name: fully wrapped
        if: ${{ success() || failure() && steps.blessed.outputs.BLESSED == '1' }}
        run: echo "hi"
      - name: fully wrapped logic-nested
        if: ${{ (success() || failure()) && steps.blessed.outputs.BLESSED == '1' }}
        run: echo "hi"

      - name: mixed
        if: success() || failure() && ${{ steps.blessed.outputs.BLESSED == '1' }}
        run: echo "hi"
      - name: mixed logic-nested
        if: (success() || failure()) && ${{ steps.blessed.outputs.BLESSED == '1'}}
        run: echo "hi"

      - name: doomed
        id: doomed
        run: |
          echo "DOOMED=1" >> $GITHUB_OUTPUT

      - name: plain
        if: success() || failure() && steps.doomed.outputs.DOOMED == '1'
        run: echo "hi"
      - name: plain logic-nested
        if: (success() || failure()) && steps.doomed.outputs.DOOMED == '1'
        run: echo "hi"

      - name: fully wrapped
        if: ${{ success() || failure() && steps.doomed.outputs.DOOMED == '1' }}
        run: echo "hi"
      - name: fully wrapped logic-nested
        if: ${{ (success() || failure()) && steps.doomed.outputs.DOOMED == '1' }}
        run: echo "hi"

      - name: mixed
        if: success() || failure() && ${{ steps.doomed.outputs.DOOMED == '1' }}
        run: echo "hi"
      - name: mixed logic-nested
        if: (success() || failure()) && ${{ steps.doomed.outputs.DOOMED == '1'}}
        run: echo "hi"
