name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    steps:
      # - uses: neuralmagic/nm-actions/actions/install-automation-components@v1.0.0
      - uses: neuralmagic/nm-actions/actions/install-testmo@v1.0.0

      - shell: bash
        run: |
          echo "== node =="
          node --version
          which node
          echo "== node =="
          npx --version
          which npx
          echo $PATH

      - uses: neuralmagic/nm-actions/actions/testmo-create-resources@dmk/testmo_resources_2
        with:
          testmo_token: "bobby"
          resources_file: "resources.json"
          resources_json: '{"monkey_see": "monkey_do"}'
