name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      blessed: steps.blessed.outputs.BLESSED
      doomed: steps.doomed.outputs.DOOMED

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-shell
