name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dbarbuzzi/actions/actions/step-status@main
        with:
          status: '0'
