name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: blessed
        id: blessed
        run: echo "BLESSED=1" >> $GITHUB_OUTPUT

      - name: doomed
        id: doomed
        run: |
          echo "DOOMED=1" >> $GITHUB_OUTPUT

      - name: check s1
        if: (success() || failure())
        run: echo "hi"

      - name: check s2
        if: ${{ success() || failure() }}
        run: echo "hi"
