name: "on-read-labeled PR action"

on: [push]

jobs:

  PR-TEST-REDUX:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      NAME: "John Doe"
      UNCERTAIN: ${NAME} - ${{ github.env.NAME }}

    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "NAME=${NAME}"
      - run: echo "UNCERTAIN=${UNCERTAIN}"
      # - uses: actions/checkout@v4
      # - uses: ./.github/actions/python-shell
