name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: bash functions
        shell: bash
        run: |
          step_status() {
            # echo "green encased checkmark" if "${1} == 0"
            # echo "red X"                   if "${1} != 0"

            if [ "$1" -eq 0 ]; then
              # green check
              echo -e "\xE2\x9C\x85"
            else
              # red x
              echo -e "\xE2\x9D\x8C"
            fi
          }

          step_status 0
          step_status 1
          step_status -127
