name: "on-push action"

on:
  push:
  workflow_dispatch:

jobs:
  Run-Action:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: dbarbuzzi/actions
      - uses: ./.github/actions/python-shell
