name: "on-read-labeled PR action"

on:
  pull_request:
    branches: main
    types: [labeled, synchronize]
  push:
    branches: main

jobs:
  PR-TEST-REDUX:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ready')
    defaults:
      run:
        shell: bash

    steps:
      - run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-shell
