name: Trigger tests

on:
  push:
  workflow_dispatch:

jobs:
  Run-Nightly-Tests:
    name: Run Nightly Tests
    strategy:
      fail-fast: false
      matrix:
        is_weekly_or_release: ["false"]
        test-config:
          - python: 3.9
            label: k8s-h100-solo
            timeout: 150
          - python: 3.10
            label: k8s-a100-quad
            timeout: 180
          - python: 3.11
            label: k8s-h100-duo
            timeout: 150
          - python: 3.12
            label: k8s-a100-duo
            timeout: 180
        exclude:
          - test-config: 3.10
            is_weekly_or_release: false
          - test-config: 3.11
            is_weekly_or_release: false

    uses: ./.github/workflows/run-tests.yml
    with:
      label: ${{ matrix.test-config.label }}
      python: ${{ matrix.test-config.python }}
      timeout: ${{ matrix.test-config.timeout }}

  Run-Weekly-Tests:
    name: Run Weekly Tests
    strategy:
      fail-fast: false
      matrix:
        is_weekly_or_release: ["true"]
        include:
          - python: 3.9
            label: k8s-h100-solo
            timeout: 150
          - python: 3.10
            label: k8s-a100-quad
            timeout: 180
          - python: 3.11
            label: k8s-h100-duo
            timeout: 150
          - python: 3.12
            label: k8s-a100-duo
            timeout: 180
        exclude:
          - python: 3.10
            label: k8s-a100-quad
            timeout: 180
            is_weekly_or_release: false
          - python: 3.11
            label: k8s-h100-duo
            timeout: 150
            is_weekly_or_release: false

    uses: ./.github/workflows/run-tests.yml
    with:
      label: ${{ matrix.label }}
      python: ${{ matrix.python }}
      timeout: ${{ matrix.timeout }}
